services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge